version: "3.5"

services:
  redis:
    image: redis
    ports:
    - "6379:6379"

  redisCommanderLocal:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8081:8081"

  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
